### ISSUE TITLE
Wait for MySQL to start up instead of crash-looping

### ISSUE THREAD

**Issue by enisoc** [youtube/vitess#2397]
In an environment like Kubernetes, vttablet and mysqld may be launched at the same time. If vttablet tries to connect to mysqld too soon, it will fail and crash-loop until mysqld is ready.

Previously, I addressed this by having vttablet wait until mysqld was ready before trying to connect to it:

https://github.com/youtube/vitess/blob/2d25adce4a38e120e80d81adae0e228d0ecb6a8f/go/vt/mysqlctl/backup.go#L515

However, there is now more going on before that point (in particular, populating local_metadata) and the crash-looping has come back:

```
I1220 21:07:01.485333       1 backup.go:728] Restore: looking for a suitable backup to restore
E1220 21:07:01.580171       1 backup.go:742] No backup to restore on BackupStorage for directory test_keyspace/0. Starting up empty.
I1220 21:07:01.580910       1 metadata_tables.go:39] Populating _vt.local_metadata table...
RestoreFromBackup failed: Can't restore backup: Can't connect to local MySQL server through socket '/vt/vtdataroot/vt_0039206302/mysql.sock' (2) (errno 2002) (sqlstate HY000)
F1220 21:07:01.581087       1 action_agent.go:258] RestoreFromBackup failed: Can't restore backup: Can't connect to local MySQL server through socket '/vt/vtdataroot/vt_0039206302/mysql.sock' (2) (errno 2002) (sqlstate HY000)
```

Can we move the "wait for MySQL" step earlier in the process so vttablet can be gracefully started up at the same time as mysqld?

**Comment by derekperkins** [comment]
Should be solved by #3530

**Comment by enisoc** [comment]
I think that will only fix one source of crash-looping (missing my.cnf). It will probably still crash-loop on missing mysql.sock unless we add a Wait() in the right place.
