### ISSUE TITLE
Support multiple values in bulk upserts

### ISSUE THREAD

**Issue by demmer** [youtube/vitess#2951]
Currently vitess does not properly handle a query of the form `INSERT INTO <table> (c1, c2) VALUES (v1, v2),(v3, v4),... ON DUPLICATE KEY UPDATE c2=v5` in a sharded table. This is only a problem when there are multiple value sets and we are doing an upsert.

Specifically, this is properly parsed as `PlanUpsertPK`:
 `INSERT INTO <table> (c1, c2) VALUES (v1, v2) ON DUPLICATE KEY UPDATE c2=xyz`

This is chopped up and processed as a set of `PlanInsertPK` operations based on the shard key:
`INSERT INTO <table> (c1, c2) VALUES (v1, v2),(v3, v4),...`

However this seems to be processed as `PlanPassDML`:
`INSERT INTO <table> (c1, c2) VALUES (v1, v2),(v3, v4),... ON DUPLICATE KEY UPDATE c2=xyz`

There is a check that seems to be only triggered when SBR but fails this query with the error "unsupported: cannot identify primary key of statement".

As @sougou and I discussed, we should be able to break up the multi-upsert into individual upserts and route them as we do for the standard insert case.

I will try to get some time to put together a PR for this but wanted to file the issue to not forget.

**Comment by demmer** [comment]
Fixed in #3066

**Comment by saikrishna4d8** [comment]
Hi, I am still facing the same issue, 
Caused by: java.sql.SQLSyntaxErrorException: vtgate: http://vtgate-zone1-********:***/: target: ***.0.master, used tablet: zone1-*** (zone1-***-0-replica-0.vttablet): vttablet: rpc error: code = Unimplemented desc = unsupported: **cannot identify primary key of statement** (CallerID: userData1)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]

FYI: I am trying to do insert/update from springboot data-jpa and i am having few additional fields in spring boot's ID class than the keys defined in vitees tables.

**Comment by harshit-gangal** [comment]
I think this was an issue with SBR bin log. Can you verify that and if in SBR can you move to RBR.

**Comment by saikrishna4d8** [comment]
Hi @harshit-gangal ,
I am new to vitesse, i tried to find the logs but i couldn't, can u please guide me with the bilog folder location or any documentation to do that.
