### ISSUE TITLE
Support 'show tables from <keyspace_name>'

### ISSUE THREAD

**Issue by dweitzman** [youtube/vitess#3578]
Right now you would have to run `show tables from vt_<keyspace_name>_0` because vitess isn't rewriting the keyspace name in the query.

Also, vtgate isn't yet clever enough to identify the keyspace to route to based on the from clause in a show tables query.

This issue is particularly troublesome with the mysql jdbc driver, since it silently swallows errors if you do connection.getMetaData().getTables() and returns an empty list instead of an exception:

https://github.com/mysql/mysql-connector-j/blob/1f61b0b0270d9844b006572ba4e77f19c0f230d4/src/com/mysql/jdbc/DatabaseMetaData.java#L4648

**Comment by yuananf** [comment]
Should be fixed by #3992

**Comment by birladeanuadrian** [comment]
Hello. I am using workbench version 8.0.16 and did a vitess setup based on the image `vitess/base:mysql80`. I still get the following errors:
```
Error Code: 1049 vtgate: http://vtgate-cluj-9hf4m:15001/: target: test_keyspace.80-.master, used tablet: cluj-200 (10.1.2.44): vttablet: rpc error: code = InvalidArgument desc = Unknown database 'test_keyspace' (errno 1049) (sqlstate 42000) (CallerID: ): Sql: "SHOW FULL COLUMNS FROM `test_keyspace`.`messages`", BindVars: {}
```
and similar for `show triggers`.

**Comment by dweitzman** [comment]
You'd need to update https://github.com/vitessio/vitess/blob/9cd0b116201893bb4b948ffc50c09b836f9b6e5a/go/vt/vtgate/executor.go#L735 to route "show columns" correctly, which might also need a parser change similar to the one in #3992.

Triggers are not currently compatible with vitess shard splitting. You could potentially implement support for "show triggers" and use them with unsharded keyspaces, but if you wanted to make triggers resharding-compatible it would probably involved new code to disable triggers during vreplication re-enable them as part of shard master migration.
